<?php

declare(strict_types=1);

return [
    'hero' => [
        'name' => 'Hero',
        'icon' => 'hero',
        'category' => 'content',
        'settings_form' => \App\Http\Requests\Modules\HeroModuleRequest::class,
        'view' => 'modules.hero',
        'description' => 'Hero section with title, subtitle, image, and CTA',
    ],
    'rich_text' => [
        'name' => 'Rich Text',
        'icon' => 'text',
        'category' => 'content',
        'settings_form' => \App\Http\Requests\Modules\RichTextModuleRequest::class,
        'view' => 'modules.rich-text',
        'description' => 'WYSIWYG content block',
    ],
    'image' => [
        'name' => 'Image',
        'icon' => 'image',
        'category' => 'media',
        'settings_form' => \App\Http\Requests\Modules\ImageModuleRequest::class,
        'view' => 'modules.image',
        'description' => 'Single image with optional caption',
    ],
    'banner' => [
        'name' => 'Banner',
        'icon' => 'banner',
        'category' => 'marketing',
        'settings_form' => \App\Http\Requests\Modules\BannerModuleRequest::class,
        'view' => 'modules.banner',
        'description' => 'Promotional banner',
    ],
    'menu' => [
        'name' => 'Menu',
        'icon' => 'menu',
        'category' => 'catalog',
        'settings_form' => \App\Http\Requests\Modules\MenuModuleRequest::class,
        'view' => 'modules.menu',
        'description' => 'Product menu/catalog',
    ],
    'products_grid' => [
        'name' => 'Products Grid',
        'icon' => 'grid',
        'category' => 'catalog',
        'settings_form' => \App\Http\Requests\Modules\ProductsGridModuleRequest::class,
        'view' => 'modules.products-grid',
        'description' => 'Grid of products',
    ],
    'categories_list' => [
        'name' => 'Categories List',
        'icon' => 'list',
        'category' => 'catalog',
        'settings_form' => \App\Http\Requests\Modules\CategoriesListModuleRequest::class,
        'view' => 'modules.categories-list',
        'description' => 'List of categories',
    ],
    'gallery' => [
        'name' => 'Gallery',
        'icon' => 'gallery',
        'category' => 'media',
        'settings_form' => \App\Http\Requests\Modules\GalleryModuleRequest::class,
        'view' => 'modules.gallery',
        'description' => 'Image gallery',
    ],
    'cta' => [
        'name' => 'Call to Action',
        'icon' => 'cta',
        'category' => 'marketing',
        'settings_form' => \App\Http\Requests\Modules\CtaModuleRequest::class,
        'view' => 'modules.cta',
        'description' => 'Call to action button/link',
    ],
    'map' => [
        'name' => 'Map',
        'icon' => 'map',
        'category' => 'contact',
        'settings_form' => \App\Http\Requests\Modules\MapModuleRequest::class,
        'view' => 'modules.map',
        'description' => 'Google Maps embed',
    ],
    'opening_hours' => [
        'name' => 'Opening Hours',
        'icon' => 'clock',
        'category' => 'contact',
        'settings_form' => \App\Http\Requests\Modules\OpeningHoursModuleRequest::class,
        'view' => 'modules.opening-hours',
        'description' => 'Business hours display',
    ],
    'contact_card' => [
        'name' => 'Contact Card',
        'icon' => 'contact',
        'category' => 'contact',
        'settings_form' => \App\Http\Requests\Modules\ContactCardModuleRequest::class,
        'view' => 'modules.contact-card',
        'description' => 'Contact information card',
    ],
    'faq' => [
        'name' => 'FAQ',
        'icon' => 'faq',
        'category' => 'content',
        'settings_form' => \App\Http\Requests\Modules\FaqModuleRequest::class,
        'view' => 'modules.faq',
        'description' => 'Frequently asked questions',
    ],
    'testimonials' => [
        'name' => 'Testimonials',
        'icon' => 'testimonials',
        'category' => 'marketing',
        'settings_form' => \App\Http\Requests\Modules\TestimonialsModuleRequest::class,
        'view' => 'modules.testimonials',
        'description' => 'Customer testimonials',
    ],
];
